Fix boolean logic error in module.server.null_resource.missing_emails for 0.12
This patch fixes a boolean logic error introduced in 3f96757.

       Error: Error running command 'false': exit status 1. Output:

       >>>>>> ------Exception-------
       >>>>>> Class: Kitchen::ActionFailed
       >>>>>> Message: 1 actions failed.
       >>>>>>     Converge failed on instance <simple-example-local>.