Fix make check_terraform examples/external_ip
Without this patch the lint checks fail because the input variable type
became more restrictive in the conversion to Terraform 0.12.  This patch
fixes the problem by accepting an arbitrary map for client and server IP
configuration.  The map is passed verbatim to client_access_config  and
as such the schema need not be replicated inside of the module.

Error fixed:

    test/terraform_validate ./examples/external_ip

    Error: Invalid value for module argument

      on main.tf line 67, in module "forseti-install-simple":
      67:   client_access_config = {
      68:     nat_ip = google_compute_address.forseti_client_ip.address
      69:   }

    The given value is not suitable for child module variable
    "client_access_config" defined at ../../variables.tf:665,1-32: attributes
    "network_tier" and "public_ptr_domain_name" are required.